export const TRADES = [
  "All",
  "Acoustical Ceiling",
  "Architect",
  "Asbestos Abatement",
  "Asphalt Paving",
  "Boiler Installation",
  "Bricklaying",
  "Cabinetry",
  "Carpentry",
  "Carpet Installation",
  "Ceramic Tile",
  "Civil Engineer",
  "Concrete",
  "Demolition",
  "Doors & Hardware",
  "Drywall",
  "Earthwork & Grading",
  "Electrical",
  "Elevator Installation",
  "Engineer - Civil",
  "Engineer - Mechanical",
  "Engineer - Structural",
  "Excavation",
  "Fencing",
  "Fire Protection",
  "Fireproofing",
  "Flooring",
  "Framing",
  "Garage Doors",
  "General Contractor",
  "Glass & Glazing",
  "Gutters",
  "HVAC",
  "Insulation",
  "Irrigation",
  "Landscape Architect",
  "Landscaping",
  "Land Surveyor",
  "Masonry",
  "Mechanical",
  "Millwork",
  "Painting",
  "Plumbing",
  "Roofing",
  "Rough Carpentry",
  "Scaffolding",
  "Siding",
  "Site Utilities",
  "Steel Erection",
  "Stone Work",
  "Stucco",
  "Surveyor",
  "Tile & Stone",
  "Waterproofing",
  "Windows",
] as const;

export type Trade = typeof TRADES[number];
